name: CI-CD to EC2 (systemd)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build jar
        run: ./gradlew clean bootJar -x test

      - name: Upload jar to EC2 (releases/)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/opt/plus/releases/"
          strip_components: 2

      - name: Switch symlink & restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            ls -t /opt/plus/releases/*.jar | head -n 1 | while read JAR; do
              echo "Latest: $JAR"
              ln -sfn "$JAR" /opt/plus/app.jar
            done
            sudo systemctl restart todo-management.service
            sudo systemctl status todo-management.service --no-pager --full || true
